name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Deploy to server (via SSH)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          GCP_KEY: ${{ secrets.GCP_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          echo "$GCP_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json

          ssh -i private_key -o StrictHostKeyChecking=no riteshgupta0968@$SERVER_IP << 'EOF'
            cd /home/riteshgupta0968/susanskar/server
            git pull
            npm install
            pm2 restart all

            cd /home/riteshgupta0968/susanskar/client
            npm run build

            sudo nginx -t
            sudo systemctl restart nginx
          EOF

          rm -f private_key gcp-key.json

